### ISSUE TITLE
可以向您了解一下知识之海吗？

### ISSUE THREAD

**Issue by LuoWalker** [shuchangxiao/school_tribune#1]
不好意思打扰了！无意占用资源！想问一下你觉得这个知识之海188值得吗？
（右下角可以删除issue）

**Comment by shuchangxiao** [comment]
还行，我准备转JAVA的，一直也是听白马老师的课的，主要是把jwt那部分弄完，让自己简历有点东西，188其实还好，我是直接买的永久的，毕竟一直在看他的课，也算支持吧，给你截一下里面的内容大概吧
![Uploading image.png…]()

**Comment by LuoWalker** [comment]
76477154@qq.com，这是我的邮箱，可以详细聊聊吗？不知道是不是我的问题，我这里看不到图片。
![image](https://github.com/shuchangxiao/school_tribune/assets/45854908/3813615e-5173-4661-a58b-0bd19cb8cf77)

**Comment by LuoWalker** [comment]
还是不能显示图片😭我就是想问一下里面只有系统监控、校园论坛和网站部署三个比较完整的项目吗？



来自 meizu 17



-------- 原始邮件 --------
发件人：shuchangxiao ***@***.***>
时间：2024年5月4日 10:26
收件人：shuchangxiao/school_tribune ***@***.***>
抄送：Walker ***@***.***>,Author ***@***.***>
主题：Re: [shuchangxiao/school_tribune] 可以向您了解一下知识之海吗？ (Issue #1)


还行，我准备转JAVA的，一直也是听白马老师的课的，主要是把jwt那部分弄完，让自己简历有点东西，188其实还好，我是直接买的永久的，毕竟一直在看他的课，也算支持吧，给你截一下里面的内容大概吧
[Uploading image.png…]

**Comment by shuchangxiao** [comment]
是的

**Comment by LuoWalker** [comment]
谢谢
